services:
  cloudpub:
    image: cloudpub/cloudpub:latest
    container_name: ${CLOUDPUB_CONTAINER}
    environment:
      - TOKEN=${CLOUDPUB_TOKEN}
      - HTTP=host.docker.internal:7777,host.docker.internal:7778
    command: run
    volumes:
      - cloudpub-config:/home/cloudpub

volumes:
  cloudpub-config: