services:
  warehouse-control_main-server:
    image: ghcr.io/golovanevvs/warehouse-control_main-server:${APP_VERSION:-latest}
    container_name: ${APP_CONTAINER}
    environment:
      - ENV=prod
      - APP_SERVICE_JWT_SECRET=${APP_SERVICE_JWT_SECRET}
      - APP_SERVICE_JWT_ACCESS_TOKEN_EXPIRY=${APP_SERVICE_JWT_ACCESS_TOKEN_EXPIRY}
      - APP_SERVICE_JWT_REFRESH_TOKEN_EXPIRY=${APP_SERVICE_JWT_REFRESH_TOKEN_EXPIRY}
      - APP_TRANSPORT_HTTP_PUBLIC_HOST=https://${PUBLIC_HOST_DOCKER}/${APP_CONTAINER}
      - APP_TRANSPORT_HTTP_WEB_PUBLIC_HOST=https://${PUBLIC_HOST_DOCKER}/${WEB_CLIENT_CONTAINER}
      - APP_TRANSPORT_HTTP_PORT=${APP_TRANSPORT_HTTP_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
      - POSTGRES_MASTER_PORT=${POSTGRES_MASTER_PORT}
      - POSTGRES_MASTER_HOST=${POSTGRES_MASTER_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - proxy
    ports:
      - 7789:${APP_TRANSPORT_HTTP_PORT}

networks:
  proxy:
    external: true