global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'delayed-notifier'
    static_configs:
      - targets: ['app:7777']
    metrics_path: /metrics

  - job_name: 'shortener'
    static_configs:
      - targets: ['app:7779']
    metrics_path: /metrics

  - job_name: 'node'
    static_configs:
      - targets: ['172.17.0.1:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
