services:
  event-booker_main-server:
    image: ghcr.io/golovanevvs/event-booker_main-server:${APP_VERSION:-latest}
    container_name: ${APP_CONTAINER}
    environment:
      - ENV=prod
      - APP_TRANSPORT_HTTP_PUBLIC_HOST=https://${PUBLIC_HOST_DOCKER}/${APP_CONTAINER}
      - APP_TRANSPORT_HTTP_WEB_PUBLIC_HOST=https://${PUBLIC_HOST_DOCKER}/${WEB_CLIENT_CONTAINER}
      - APP_TRANSPORT_HTTP_PORT=${APP_TRANSPORT_HTTP_PORT}
      - APP_REPOSITORY_FILE_STORAGE_DIR=${APP_REPOSITORY_FILE_STORAGE_DIR}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
      - POSTGRES_MASTER_PORT=${POSTGRES_MASTER_PORT}
      - POSTGRES_MASTER_HOST=${POSTGRES_MASTER_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - event-booker_storage:/root/resources/app/filestorage
    networks:
      - proxy
      - event-booker_main-server
    ports:
      - 7785:${APP_TRANSPORT_HTTP_PORT}

volumes:
  event-booker_storage:
    driver: local

networks:
  proxy:
    external: true
  event-booker_main-server:
    driver: bridge
    name: event-booker_main-server 