services:
  cloudpub-webhook:
    image: cloudpub/cloudpub:latest
    container_name: ${CLOUDPUB_WEBHOOK_CONTAINER}
    environment:
      - TOKEN=${CLOUDPUB_WEBHOOK_TOKEN}
      - HTTP=host.docker.internal:9000
    command: run
    volumes:
      - cloudpub-webhook-config:/home/cloudpub

volumes:
  cloudpub-webhook-config: